//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoricalTrackingDemo {
    
    
    public partial class _Default {
        
        /// <summary>
        /// lnkFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkFilter;
        
        /// <summary>
        /// ctlHistoricalDataViewer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HistoricalTrackingDemo.Controls.ctlHistoricalDataViewer ctlHistoricalDataViewer;
        
        /// <summary>
        /// ctlFilteredHistoricalDataViewer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HistoricalTrackingDemo.Controls.ctlFilteredHistoricalDataViewer ctlFilteredHistoricalDataViewer;
    }
}
